name: virtual-kubelet-lint

on:
  push:
    branches:
      - master
      - release-*
  workflow_dispatch: {}
  pull_request:
    branches:
      - master
      - release-*
    paths-ignore: [docs/**, "**.md", "**.mdx", "**.png", "**.jpg"]

env:
  # Common versions
  GO_VERSION: '1.15'

jobs:

  detect-noop:
    runs-on: ubuntu-latest
    outputs:
      noop: ${{ steps.noop.outputs.should_skip }}
    steps:
      - name: Detect No-op Changes
        id: noop
        uses: fkirc/skip-duplicate-actions@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          do_not_skip: '["workflow_dispatch", "schedule", "push"]'
          concurrent_skipping: false

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: /go/pkg/mod
          key: validate-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
          restore-keys: validate-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
      - name: go vet
        run: |
          V=1 CI=1 make vet

      - name: golangci-lint
        run: make lint

      - name: Dependencies
        run: |
          scripts/validate/gomod.sh